[cursor]
style = "Block"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[shell]
program = "/usr/bin/fish"

[window]
opacity = 0.9
startup_mode = "Maximized"
