#[](#274e13)\
#[](bg:#3ba55d fg:#3ba55d)\
#[](fg:#00ff80 bg:#00ff80)\
#[](fg:#3a63f4 bg:#3a63f4)\
#[](fg:#052e53 bg:#052e53)\
#$time\

format = """
$username\
$directory\
$git_branch\
$git_status\
$c\
$cmake\
$java\
$python\
$rust\
$status\
"""

# Disable the blank line at the start of the prompt
# add_newline = false


# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#228b22"
style_root = "fg:#c70039"
format = ' [$user]($style)'

[directory]
# style = "bg:#84a590 fg:#28282B"
format = " $path "
truncation_length = 3
truncation_symbol = "../"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

#[time]
#disabled = false
#time_format = "%R" # Hour:Minute Format
#style = "bg:#3a63f4"
#format = '[[ $time ](bg:#3a63f4)]($style)'


[status]
success_symbol = " [  ](#228b22)"
symbol = " [ ❌ ](bold red)"
sigint_symbol = "[ ❌](bold yellow)"
not_found_symbol = "[  ](bold white)"
not_executable_symbol = "[  ](bold red)"
format = "$symbol"
map_symbol = true
disabled = false
# vicmd_symbol = " [<](bold green)"

[git_branch]
symbol = " "
style = "fg:#f14e32"
format = ' [$symbol $branch]($style) '

[git_status]
style = "fg:#f14e32"
format = '[($all_status$ahead_behind)]($style)'

[python]
symbol = ""
style = "fg:#fdda0d"
# style = "bg:#0b5394 fg:#28282B"
format = ' via [$symbol ($version)]($style)'

[cmake]
symbol = "󰙲 " 
style = "fg:#89cff0"
# style = "bg:#0b5394 fg:#28282B"
format = ' via [$symbol ($version)]($style)'

[c]
symbol = ' '
style = "fg:#89cff0"
format = ' via [$symbol($version(-$name))]($style)'

[java]
symbol = " "
style = "fg:#ff0000"
# style = "bg:#0b5394 fg:#28282B"
format = ' via [$symbol ($version)]($style)'

[rust]
symbol = " "
style = "bold red"
# style = "bg:#FFFFFF,fg:#281C1C"
# style = "bg:#0b5394 fg:#28282B"
format = ' via [$symbol ($version)]($style)'
