#!/usr/bin/env bash
# BIG thanks to morrolinux (for the hint) and to luispabon (on github)

entries="⏾ Suspend\n⭮ Reboot\n⏻ Shutdown"

#selected=$(echo -e $entries|wofi --width 250 --height 210 --dmenu --cache-file /dev/null | awk '{print tolower($2)}')
selected=$(echo -e $entries|rofi --dmenu --x 0 --y 0 --width 250 --height 210 --cache-file /dev/null | awk '{print tolower($2)}')

case $selected in
  suspend)
    exec xss-lock -- i3lock -n &;;
  reboot)
    exec systemctl reboot;;
  shutdown)
    exec systemctl poweroff -i;;
esac
